#!/bin/bash
alias npmi="npm install"
alias npmid="npm install --save-dev"
alias npmig="npm install -g"
alias npmr="npm uninstall"
alias npmrg="npm uninstall -g"
alias npml="npm list --depth=0"
alias npmlg="npm list -g --depth=0"
alias npmunit="clear; npm run unit"
alias serve="clear; npm run serve"
